# Analysis options for VolleyPass Mobile
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "build/**"
    - ".dart_tool/**"

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    missing_required_param: error
    missing_return: error
    todo: info

linter:
  rules:
    - avoid_print
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - require_trailing_commas
    - always_declare_return_types
    - annotate_overrides
    - avoid_unnecessary_containers
    - use_key_in_widget_constructors
    - prefer_single_quotes
