# ============================================================================
# GITHUB ACTION ROBUSTO PARA VOLLEYPASS (RAMA MAIN)
# Archivo: .github/workflows/deploy.yml
# Repositorio: korozcolt/volleypass
# ============================================================================

name: Deploy VolleyPass to Kronnos.dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy VolleyPass to Production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 208.109.235.177 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no kronnos@208.109.235.177 << 'EOF'
          set -e

          # Variables
          REPO_URL="https://github.com/korozcolt/volleypass.git"
          APP_DOMAIN="volleypass.kronnos.dev"
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          RELEASE_DIR="/var/deployments/releases/$APP_DOMAIN/$TIMESTAMP"

          echo "=== INICIANDO DEPLOYMENT VOLLEYPASS ROBUSTO ==="
          echo "Timestamp: $TIMESTAMP"

          # Crear directorio de release
          mkdir -p "$RELEASE_DIR"
          cd "$RELEASE_DIR"

          # Clonar repositorio
          echo "Clonando repositorio..."
          git clone --branch main --single-branch --depth 1 "$REPO_URL" .

          # Instalar dependencias PHP
          echo "Instalando dependencias PHP..."
          composer install --no-dev --optimize-autoloader --no-interaction

          # Instalar dependencias Node.js (TODAS las dependencias incluyendo dev)
          if [[ -f "package.json" ]]; then
            echo "Instalando dependencias Node.js..."
            npm ci
            echo "Compilando assets..."
            npm run build
          fi

          # Configurar .env - MÉTODO ROBUSTO
          echo "Configurando .env..."

          ENV_SOURCE="/var/www/shared/configs/$APP_DOMAIN.env"

          if [[ -f "$ENV_SOURCE" ]]; then
            echo "Copiando .env desde configuración compartida..."
            cp "$ENV_SOURCE" .env

            # Verificar que el archivo .env es válido
            echo "Verificando archivo .env..."

            # Verificar que contiene DB_CONNECTION=mysql
            if grep -q "DB_CONNECTION=mysql" .env; then
              echo "✅ Configuración MySQL detectada"
            else
              echo "❌ No se encontró configuración MySQL, corrigiendo..."
              # Forzar configuración MySQL
              sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
              sed -i 's/DB_DATABASE=.*/DB_DATABASE=volleypass_db/' .env
              sed -i 's/DB_USERNAME=.*/DB_USERNAME=laravel/' .env
              sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=Kr0nn0s2024#Laravel/' .env
            fi

            # Asegurar que APP_KEY existe y es válida
            if ! grep -q "APP_KEY=base64:" .env; then
              echo "Generando APP_KEY..."
              php artisan key:generate --force
            fi

          else
            echo "No se encontró .env compartido, creando uno nuevo..."
            cp .env.example .env

            # Configurar para MySQL específicamente
            sed -i 's/DB_CONNECTION=.*/DB_CONNECTION=mysql/' .env
            sed -i 's/DB_HOST=.*/DB_HOST=localhost/' .env
            sed -i 's/DB_PORT=.*/DB_PORT=3306/' .env
            sed -i 's/DB_DATABASE=.*/DB_DATABASE=volleypass_db/' .env
            sed -i 's/DB_USERNAME=.*/DB_USERNAME=laravel/' .env
            sed -i 's/DB_PASSWORD=.*/DB_PASSWORD=Kr0nn0s2024#Laravel/' .env

            # Generar APP_KEY
            php artisan key:generate --force
          fi

          # Mostrar configuración para depuración
          echo "=== CONFIGURACIÓN .ENV ==="
          echo "DB_CONNECTION: $(grep 'DB_CONNECTION=' .env | cut -d'=' -f2)"
          echo "DB_DATABASE: $(grep 'DB_DATABASE=' .env | cut -d'=' -f2)"
          echo "APP_KEY configurada: $(grep 'APP_KEY=' .env | cut -d'=' -f2 | cut -c1-20)..."

          # Comandos Laravel - ORDEN CORRECTO
          echo "Ejecutando comandos Laravel..."

          # 1. Limpiar caches existentes
          echo "Limpiando caches..."
          php artisan config:clear || true
          php artisan cache:clear || true
          php artisan view:clear || true
          php artisan route:clear || true

          # 2. Verificar configuración
          echo "Verificando configuración de base de datos..."
          if ! php artisan config:show database.connections.mysql.database 2>/dev/null | grep -q "volleypass_db"; then
            echo "Problema con configuración, regenerando..."
            php artisan config:clear
          fi

          # 3. Probar conexión a base de datos
          echo "Probando conexión a base de datos..."
          if ! php artisan migrate:status >/dev/null 2>&1; then
            echo "Problema de conexión a BD, verificando credenciales..."
            # Mostrar error específico
            php artisan migrate:status || echo "Error de conexión detectado"
          fi

          # 4. Ejecutar migraciones primero
          echo "Ejecutando migraciones..."
          php artisan migrate --force

          # 5. Cachear configuración después de migraciones exitosas
          echo "Cacheando configuración..."
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          # 6. Crear enlaces de storage
          echo "Creando enlaces de storage..."
          php artisan storage:link

          # Permisos
          echo "Estableciendo permisos..."
          sudo chown -R webapps:www-data "$RELEASE_DIR"
          sudo chmod -R 755 "$RELEASE_DIR"
          sudo chmod -R 775 "$RELEASE_DIR/storage" "$RELEASE_DIR/bootstrap/cache"

          # Activar nueva versión
          echo "Activando nueva versión..."
          sudo rm -f "/var/www/$APP_DOMAIN"
          sudo ln -sf "$RELEASE_DIR" "/var/www/$APP_DOMAIN"

          # Recargar servicios
          echo "Recargando servicios..."
          sudo systemctl reload nginx php8.3-fpm

          # Limpiar releases antiguos (mantener últimos 3)
          echo "Limpiando releases antiguos..."
          cd "/var/deployments/releases/$APP_DOMAIN"
          ls -t | tail -n +4 | xargs -r rm -rf

          echo "=== DEPLOYMENT COMPLETADO ==="
          echo "VolleyPass actualizado exitosamente en https://$APP_DOMAIN"

          # Verificación final robusta
          echo "Verificando aplicación..."
          sleep 5  # Esperar a que la aplicación se estabilice

          # Probar tanto HTTP como HTTPS
          for protocol in https http; do
            if curl -s -I "$protocol://$APP_DOMAIN" | grep -q "200 OK"; then
              echo "✅ Aplicación respondiendo en $protocol://$APP_DOMAIN"
              break
            elif curl -s -I "$protocol://$APP_DOMAIN/health" | grep -q "200 OK"; then
              echo "✅ Health check OK en $protocol://$APP_DOMAIN/health"
              break
            fi
          done

          echo "🚀 Deployment completado exitosamente"
        EOF
