# ============================================================================
# GITHUB ACTION MEJORADO PARA VOLLEYPASS (RAMA MAIN)
# Archivo: .github/workflows/deploy.yml
# Repositorio: korozcolt/volleypass
# ============================================================================

name: Deploy VolleyPass to Kronnos.dev

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy VolleyPass to Production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.8.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Add server to known hosts
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 208.109.235.177 >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no kronnos@208.109.235.177 << 'EOF'
          set -e

          # Variables
          REPO_URL="https://github.com/korozcolt/volleypass.git"
          APP_DOMAIN="volleypass.kronnos.dev"
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          RELEASE_DIR="/var/deployments/releases/$APP_DOMAIN/$TIMESTAMP"

          echo "=== INICIANDO DEPLOYMENT VOLLEYPASS ==="
          echo "Timestamp: $TIMESTAMP"

          # Crear directorio de release
          mkdir -p "$RELEASE_DIR"
          cd "$RELEASE_DIR"

          # Clonar repositorio
          echo "Clonando repositorio..."
          git clone --branch main --single-branch --depth 1 "$REPO_URL" .

          # Instalar dependencias PHP
          echo "Instalando dependencias PHP..."
          composer install --no-dev --optimize-autoloader --no-interaction

          # Instalar dependencias Node.js (TODAS las dependencias incluyendo dev)
          if [[ -f "package.json" ]]; then
            echo "Instalando dependencias Node.js..."
            npm ci
            echo "Compilando assets..."
            npm run build
          fi

          # Configurar .env - MEJORADO
          echo "Configurando .env..."
          if [[ -f "/var/www/shared/configs/$APP_DOMAIN.env" ]]; then
            echo "Copiando .env desde configuración compartida..."
            cp "/var/www/shared/configs/$APP_DOMAIN.env" .env

            # Verificar que el archivo .env es válido
            if php -r "file_exists('.env') && parse_ini_file('.env') ? exit(0) : exit(1);"; then
              echo "✅ Archivo .env válido"
            else
              echo "❌ Archivo .env inválido, generando uno nuevo..."
              cp .env.example .env
              php artisan key:generate --force
            fi
          else
            echo "No se encontró .env compartido, usando .env.example..."
            cp .env.example .env
            php artisan key:generate --force
          fi

          # Mostrar información del .env para depuración
          echo "APP_KEY configurada:"
          grep "APP_KEY=" .env || echo "No APP_KEY encontrada"

          # Comandos Laravel
          echo "Ejecutando comandos Laravel..."

          # Verificar configuración antes de continuar
          echo "Verificando configuración..."
          if ! php artisan config:show app.key >/dev/null 2>&1; then
            echo "Regenerando APP_KEY..."
            php artisan key:generate --force
          fi

          # Limpiar caches antes de configurar
          php artisan config:clear
          php artisan cache:clear
          php artisan view:clear
          php artisan route:clear

          # Configurar Laravel
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache

          # Ejecutar migraciones
          echo "Ejecutando migraciones..."
          php artisan migrate --force

          # Crear enlaces de storage
          php artisan storage:link

          # Permisos
          echo "Estableciendo permisos..."
          sudo chown -R webapps:www-data "$RELEASE_DIR"
          sudo chmod -R 755 "$RELEASE_DIR"
          sudo chmod -R 775 "$RELEASE_DIR/storage" "$RELEASE_DIR/bootstrap/cache"

          # Activar nueva versión
          echo "Activando nueva versión..."
          sudo rm -f "/var/www/$APP_DOMAIN"
          sudo ln -sf "$RELEASE_DIR" "/var/www/$APP_DOMAIN"

          # Recargar servicios
          echo "Recargando servicios..."
          sudo systemctl reload nginx php8.3-fpm

          # Limpiar releases antiguos (mantener últimos 3)
          echo "Limpiando releases antiguos..."
          cd "/var/deployments/releases/$APP_DOMAIN"
          ls -t | tail -n +4 | xargs -r rm -rf

          echo "=== DEPLOYMENT COMPLETADO ==="
          echo "VolleyPass actualizado exitosamente en https://$APP_DOMAIN"
          echo "Verificando aplicación..."

          # Verificación final
          if curl -s -I "https://$APP_DOMAIN" | grep -q "200 OK"; then
            echo "✅ Aplicación respondiendo correctamente"
          else
            echo "⚠️  Aplicación puede necesitar unos minutos para estabilizarse"
          fi
        EOF
